theme: jekyll-theme-minimal
title: The Enemy of my Enemy is my Friend Theory
description: We are going to tell the story of four data nerds that are interested in The Enemy of my Enemy is my Friend Theory 
show_downloads: True
navigation:
  - title: Datastory
    url: storydata
